openapi: 3.0.1
info:
  title: Api
  version: 0.1.0
servers:
- url: "{server}:{port}/api"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /getIdentityFromNIC:
    get:
      operationId: getGetidentityfromnic
      parameters:
      - name: nic
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "202":
          description: Accepted
        "400":
          description: BadRequest
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /getPoliceRecordFromNIC:
    get:
      operationId: getGetpolicerecordfromnic
      parameters:
      - name: NIC
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "202":
          description: Accepted
        "400":
          description: BadRequest
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /getGSDivisionFromNIC:
    get:
      operationId: getGetgsdivisionfromnic
      parameters:
      - name: gsDivision
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "202":
          description: Accepted
        "400":
          description: BadRequest
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /getAddressByNIC:
    get:
      operationId: getGetaddressbynic
      parameters:
      - name: nic
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "202":
          description: Accepted
        "400":
          description: BadRequest
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /userRequest:
    post:
      operationId: postUserrequest
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
        "202":
          description: Accepted
        "400":
          description: BadRequest
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
